### ISSUE TITLE
Market Page - Internal server error after placing bid (Closed: Duplicate)

### ISSUE THREAD

**Issue by Rich-PPT** [bitpopulous/community_reviews#104]
Which Site (Platform or Website): https://beta.populous.co/invoice/KPe5Ej4Shu4hNhvs4	
Site Version (if known): 1.0
Which Page: Market> 333 Three Company Ltd > Place your bid > Bid anonymously 

What sequence of actions just before error:
Clicking on submit bid.

Problem Type (error_msg, functionality, correctness, no response, unexpected response, other ):

Error message Internal server error
Problem Duration (once, sporadic, repeated, always): Always
Brief Description (expand as needed, be to the point):

When you place a bid and click submit bid it gives you a message that the bid was successful. After couple of seconds you get another message: Internal server error. So you receive OK message and NOT  OK message which is misleading and very confusing. 

ReporterName: David Fens		Date/Time:		20 35 GMT, 11 February	
My Device Type (Desktop, Laptop, Netbook, Pad, Pod, SmartPhone, Other): Laptop
My OS (Windows, MacOS, Linux, iOS, Android, ChromeOS, Other): Linux
My Browser (Internet Explorer, Edge, Safari, Chrome, FireFox, Opera, Other): Chromium 
My Browser Version: 63.0.3239.84

**Comment by brycewilliam** [comment]
See Issue #102
