### ISSUE TITLE
Website - 2FA Confirmation Error (Closed: Duplicate)

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/community_reviews#13]
Comment from a Slack member with regards to the 2FA even though he should not have used the beta until word is given.:

hi Everybody, i've registered to beta.popolous.co, i've received the confirmation email and i've setup the 2nd factor auth. But when i enter the code the first time i get an error, and therefore i cannot complete the login. Has anybody faced the same issue and found a solution for that? Thank you in advance for your help

**Comment by brycewilliam** [comment]
See issue #34
