### ISSUE TITLE
Login - Keep me signed in (Closed: Duplicate)

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/community_reviews#27]
I check keep me signed in and then log in successfully.  Close down the tab (not browser) and then go back to log in page immediately.  Does the "keep me signed in" check box allow me to automatically login back to my account or not because this function seem to not be working.

**Comment by woofie33** [comment]
Funny cause it actually keeps me signed in and I have not checked anything. Even if I kill the browser and restart it.  Chrome browser on Mac
