### ISSUE TITLE
Registration - bugs (Closed: Duplicate)

### ISSUE THREAD

**Issue by PopulousMarkHarrison** [bitpopulous/community_reviews#31]
cryptostacker [2:04 PM]
Bugs while registering:  
1) unable to register with a "+" in my email.  IE sam+abc@gmail.com.  "+" character is interpretted by email servers to allow users to create email address on the fly

2) unable to use a complex password such as 8gij~[Pj2RYqxmqMb3odv  - i get a message saying my password is too weak

**Comment by Rich-PPT** [comment]
Related to issue #39

**Comment by brycewilliam** [comment]
See #39
