### ISSUE TITLE
Invoice screen hanging 

### ISSUE THREAD

**Issue by crypt0inferno** [bitpopulous/community_reviews#389]
Date and time: 28/2/2018. 11:31pm (AEST)
URL: https://beta.populous.co/invoice/pxheYMgfMGCP68D5w
User type: Investor
IOS: Windows 10 home.
Browser: Mozilla 58.0.2 (64-bit)

Steps to reproduce:
Click Market  > Click invoice: pxheYMgfMGCP68D5w (total control) 

Result: system displays the populous loading symbol and then hangs. I left the page for 5 min - no change. 

Expected result: System displays the invoice information. 

Note: This is affecting all other invoices. 

![hang](https://user-images.githubusercontent.com/36888687/36787922-069db51a-1ce0-11e8-8bea-b3bf4289dca8.JPG)

**Comment by topd333** [comment]
https://github.com/bitpopulous/platform/issues/971

**Comment by wisdomcsharp** [comment]
resolved
