### ISSUE TITLE
How do I get access to fake PPT or pokens to test buying invoices?

### ISSUE THREAD

**Issue by crypt0inferno** [bitpopulous/community_reviews#394]
I am not a populous employee, how do I get access to fake PPT or pokens to test buying invoices?

cheers,

**Comment by wisdomcsharp** [comment]
Contact mark harrison on the slack channel, or possibly via telegram.
bitpopulous.slack.com

**Comment by crypt0inferno** [comment]
Thanks Wisdom will do
