### ISSUE TITLE
Add Invoice - Debtor name does not allow a space to be entered.

### ISSUE THREAD

**Issue by Rich-PPT** [bitpopulous/community_reviews#539]
Which Site (Platform or Website): https://beta.populous.co/add-invoice	Site Version (if known):
Which Page: Add invoice 1st page
What sequence of actions just before error:
Problem Type (error_msg, functionality, correctness, no response, unexpected response, other ): Correctness
Problem Duration (once, sporadic, repeated, always): Always
Brief Description (expand as needed, be to the point):

Debtor cannot contain space. So completely legit debtor name e.g. David Fens cannot be entered. Please set more precise rules for allowed characters. Space is OK as long it is not the only character or the first one. None of the other “special” characters are allowed like - & / … Ampersand is probably a legit character for a debtor name. Please put more consideration into a list of allowed characters. 

![image](https://user-images.githubusercontent.com/36181372/37686542-263680e4-2c55-11e8-8d29-e40432ff62da.png)

ReporterName: David Fens		Date/Time:		21 00  GMT, 20 March	
My Device Type (Desktop, Laptop, Netbook, Pad, Pod, SmartPhone, Other): Laptop
My OS (Windows, MacOS, Linux, iOS, Android, ChromeOS, Other): Linux
My Browser (Internet Explorer, Edge, Safari, Chrome, FireFox, Opera, Other): Chromium 
My Browser Version: 63.0.3239.84

**Comment by wisdomcsharp** [comment]
IGNORE.
Being replaced with a verified list of debtors.
