### ISSUE TITLE
Market Invoice - There are no currency options to select from (Closed: Duplicate)

### ISSUE THREAD

**Issue by PopulousMarkHarrison** [bitpopulous/community_reviews#63]
SITE:  Website - Beta.populous.co
Which Page: market invoice

What sequence of actions just before error:

Drop down menu for currency market

Problem Type (error_msg, functionality, correctness, no response, unexpected response, other ):
Functionality

Problem Duration (once, sporadic, repeated, always):

Brief Description (expand as needed, be to the point):
There are no currency options to select from

ReporterName:	Reina Jackson
Date/Time:	feb 9, 10:07 pm pst

My Device Type (Desktop, Laptop, Netbook, Pad, Pod, SmartPhone, Other): iphone7+
My OS (Windows, MacOS, Linux, iOS, Android, ChromeOS, Other): IOS
My Browser (Internet Explorer, Edge, Safari, Chrome, FireFox, Opera, Other): Chrome
My Browser Version:

**Comment by brycewilliam** [comment]
See Issue #16
