### ISSUE TITLE
Market  - most of the Filters and Search Criteria do not work. (Closed: Duplicate)

### ISSUE THREAD

**Issue by PopulousMarkHarrison** [bitpopulous/community_reviews#64]
Which Site (Platform or Website):			Site Version (if known): Beta
Which Page: Market

What sequence of actions just before error:   Most of the Filters and Search Criteria in the Market Tab does not work.

Problem Type (error_msg, functionality, correctness, no response, unexpected response, other ):  Functionality/No Response

Problem Duration (once, sporadic, repeated, always): Always

Attempting to find invoices after adjusting filters results in an empty screen.
The calendars do not allow selection of dates prior to the current date.
The “Reset to Default” button does not set all fields to default.

**Comment by brycewilliam** [comment]
See Issue #49
