### ISSUE TITLE
2nd factor authentication setup (Closed: Duplicate)

### ISSUE THREAD

**Issue by PopulousMarkHarrison** [bitpopulous/community_reviews#71]
Which Site (Platform or Website): beta.popolous.co            Site Version (if known):1.0
Which Page: 2nd factor authentication setup
What sequence of actions just before error:
1)    Successful Login
2)    Scan QR Code into Google Authenticator, and press "Next" button
3)    Enter the 6 digit code and press "FINISH 2FA SETUP"Problem Type (error_msg, functionality, correctness, no response, unexpected response, other :disappointed:
It is not possible to complete the first login, because 2nd factor authentication is not working.
I receive an error saying that the code entered is not correct.

Problem Duration (once, sporadic, repeated, always): Always
Brief Description (expand as needed, be to the point): I've created the my account (francesco.bersani@gmail.com)
ReporterName: Francesco Bersani       Date/Time:            10-feb-2018 19.20 CET

My Device Type (Desktop, Laptop, Netbook, Pad, Pod, SmartPhone, Other): Laptop
My OS (Windows, MacOS, Linux, iOS, Android, ChromeOS, Other): MacOS
My Browser (Internet Explorer, Edge, Safari, Chrome, FireFox, Opera, Other): Chrome
My Browser Version: 64.0.3282.140 (Official Build) (64-bit)

**Comment by brycewilliam** [comment]
See issue #34
