### ISSUE TITLE
Login - 2FA fails displays "Error that code is invalid" (Closed: Duplicate)

### ISSUE THREAD

**Issue by Rich-PPT** [bitpopulous/community_reviews#74]
Which Site (Platform or Website): https://beta.populous.co/			Site Version (if known): 1.0
Which Page: https://beta.populous.co/login

What sequence of actions just before error: Logged out then tried to log in

Problem Type (error_msg, functionality, correctness, no response, unexpected response, other ):
When trying to log in the 2FA error message displays and login fails.

Problem Duration (once, sporadic, repeated, always): Always

Brief Description (expand as needed, be to the point):
When trying to log in the 2FA error message displays and login fails.

ReporterName: Rich.S		Date/Time: 2/10/201/ 12:41 pm		
My Device Type (Desktop, Laptop, Netbook, Pad, Pod, SmartPhone, Other): Desktop PC
My OS (Windows, MacOS, Linux, iOS, Android, ChromeOS, Other): Windows
My Browser (Internet Explorer, Edge, Safari, Chrome, FireFox, Opera, Other): Firefox
My Browser Version: 58.0.2 (64-bit)

**Comment by Rich-PPT** [comment]
This is intermittent, I just logged in and the Google 2FA worked then I logged out and now I can't log back in.

**Comment by Rich-PPT** [comment]
I reloaded the site and could now log in again.

**Comment by brycewilliam** [comment]
Duplicate with Issue #34
